        --------------------------------------------
	--
	--		Copyright：PERFECT WORLD
	--		Modified：2012/11/10
	--		Author：向珈辰 
	--		Class: Lua
	--		AIName：11981_monster_toumingguai.lua
	--		Backup：隐藏怪 AI
	---------------------------------------------        
--    function Event_OnTimer(nAI, nIndex, nCount)
--         local AI = GetMonsterAI(nAI)			
--    end	
--    	
--    	
--    function Event_Thinking(nAI)
--        local AI = GetMonsterAI(nAI)
--        local mapid = AI:GetMapID()
--        local swich = AI:GetEctypeVarShort(mapid , 0)
--        a = AI:GetArray(0)   
--       	--出生即刷新城门
--        if a == 0 then
--        	if swich == 0 then
----    			AI:AddGuildDomainMonster( 59253 , 163.8 , 87.7 , 0 , 0 , 0 , 0 )
----    			AI:AddGuildDomainMonster( 59254 , 106.7 , 66.5 , 0 , 0 , 0 , 0 )
----    			AI:AddGuildDomainMonster( 59255 , 220.9 , 66.5 , 0 , 0 , 0 , 0 )
--					end
--    			AI:SetArray(0,1)
--    		end
--
--    end	
--    
--    function Event_OnDead(nAI)
--				local AI = GetMonsterAI(nAI)
--    end			                                                                                   